"""
Stage 04: SLM Clinical Summarizer FastAPI REST API.

Provides endpoints for:
- Health checks: GET /health
- Direct note summarization: POST /summarize
- Stage 03 to Stage 04 integrated pipeline: POST /summarize_stage03
"""

import os
import sys
import logging
from typing import Optional, Dict, Any
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Ensure project root is in sys.path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
for p in [PROJECT_ROOT, SCRIPT_DIR]:
    if p not in sys.path:
        sys.path.insert(0, p)

from stage04_slm.summarizer import get_summarizer, summarize_clinical_note, ClinicalSummarizer
from stage04_slm.safety_guardrail import ClinicalSummarySafetyGuardrail

logger = logging.getLogger("stage04_slm.api")
if not logger.handlers:
    logging.basicConfig(level=logging.INFO, format="[%(asctime)s] [%(levelname)s] %(name)s: %(message)s")


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Eagerly loads model on server startup and cleanly releases on shutdown."""
    logger.info("Initializing Stage 04 SLM service during startup...")
    try:
        get_summarizer()
        logger.info("Stage 04 SLM service successfully initialized and ready.")
    except Exception as e:
        logger.warning(f"Deferred model loading on startup: {e}. Model will load on first inference request.")
    yield
    logger.info("Shutting down Stage 04 SLM service.")


app = FastAPI(
    title="Personalized Precision Medicine - Stage 04 SLM Summarizer API",
    description=(
        "REST API serving the fine-tuned Qwen2.5-3B + LoRA Clinical Summarization Model. "
        "Strictly provides faithful summarization with clinical safety guardrails. "
        "Intended for decision support only — not an autonomous diagnostic system."
    ),
    version="1.0.0",
    lifespan=lifespan
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ==============================================================================
# REQUEST & RESPONSE SCHEMAS
# ==============================================================================

class HealthResponse(BaseModel):
    status: str = Field(..., json_schema_extra={"example": "ok"})
    stage: str = Field(..., json_schema_extra={"example": "Stage 04 SLM"})
    model: Optional[str] = "Qwen/Qwen2.5-3B + LoRA"
    device: Optional[str] = None


class SummarizeRequest(BaseModel):
    clinical_report: str = Field(
        ...,
        description="Unstructured oncology clinical note narrative.",
        json_schema_extra={"example": "Trial screening EGFR L858R prior/current drug Pembrolizumab dose 300mg twice daily symptoms severe diarrhea ae nausea"}
    )
    # Disallow patient_id leakage into prompt
    patient_id: Optional[str] = Field(None, description="Patient identifier (filtered out from model input to prevent privacy/leakage issues).")


class SummarizeResponse(BaseModel):
    summary: str = Field(..., description="Faithful, concise clinical summary generated by Stage 04 SLM.")


class Stage03IngestRequest(BaseModel):
    clinical_report: str = Field(..., description="Raw clinical narrative note.")
    urgency: Optional[str] = Field(None, description="Stage 03 Urgency classification (High, Moderate, Low).")
    entities: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Stage 03 extracted Medical NER entities (gene_mutation, drug_name, dosage, adverse_event)."
    )
    patient_id: Optional[str] = Field(None, description="Patient ID for tracing only (never passed to generative prompt).")


class Stage06ReadyResponse(BaseModel):
    summary: str = Field(..., description="Faithful clinical summary generated by Stage 04 SLM.")
    urgency: str = Field(..., description="Clinical triage urgency.")
    entities: Dict[str, Any] = Field(..., description="Structured clinical entities.")
    safety_status: str = Field(..., description="'passed' or 'flagged'")
    safety_validation: Dict[str, Any] = Field(..., description="Detailed safety guardrail audit report.")


# ==============================================================================
# API ENDPOINTS
# ==============================================================================

@app.get("/health", response_model=HealthResponse)
def health_check():
    """
    Health check endpoint returning service readiness and stage metadata.
    """
    try:
        summarizer = get_summarizer()
        device_str = str(summarizer.bundle.device)
        model_str = f"{summarizer.bundle.base_model_name} + LoRA ({summarizer.bundle.adapter_path})"
    except Exception:
        device_str = "uninitialized"
        model_str = "Qwen/Qwen2.5-3B + LoRA"

    return HealthResponse(
        status="ok",
        stage="Stage 04 SLM",
        model=model_str,
        device=device_str
    )


@app.post("/summarize", response_model=SummarizeResponse)
def summarize_endpoint(request: SummarizeRequest):
    """
    Generates a concise, faithful summary from an input clinical report.
    """
    report_text = request.clinical_report.strip() if request.clinical_report else ""
    if not report_text:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="clinical_report must not be empty."
        )

    # Prevent Patient_ID from ever entering model prompt
    if request.patient_id:
        logger.info(f"Filtered out Patient_ID '{request.patient_id}' from model input to prevent leakage.")

    try:
        summary_text = summarize_clinical_note(report_text)
        return SummarizeResponse(summary=summary_text)
    except Exception as e:
        logger.error(f"Summarization error: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Clinical summarization failed: {str(e)}"
        )


@app.post("/summarize_stage03", response_model=Stage06ReadyResponse)
def summarize_stage03_endpoint(request: Stage03IngestRequest):
    """
    Integration endpoint connecting Stage 03 NLP outputs directly to Stage 04 SLM,
    producing verified structured context for Stage 06 Multi-Agent systems.
    """
    report_text = request.clinical_report.strip() if request.clinical_report else ""
    if not report_text:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="clinical_report must not be empty."
        )

    try:
        summarizer = get_summarizer()
        result = summarizer.summarize(
            clinical_report=report_text,
            stage03_urgency=request.urgency,
            stage03_entities=request.entities
        )
        return Stage06ReadyResponse(
            summary=result["summary"],
            urgency=result["urgency"],
            entities=result["entities"],
            safety_status=result["safety_status"],
            safety_validation=result["safety_validation"]
        )
    except Exception as e:
        logger.error(f"Stage 03 -> Stage 04 processing error: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Stage 03 -> Stage 04 integration failed: {str(e)}"
        )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8004)
