"""
Stage 04: Clinical Safety & Hallucination Guardrail Layer.

Verifies factual grounding of the generated summary against the source clinical report.
Detects and flags:
1. Invented medications / antineoplastic drugs
2. Dosage and regimen mismatches
3. Unsupported genomic alterations / biomarkers
4. Unsupported symptoms
5. Unsupported adverse events / toxicities
6. Autonomous diagnostic claims
7. Prescriptive directives / treatment recommendations
8. Unauthorized clinical decision-making
"""

import re
from typing import Dict, Any, List, Set, Optional

# Oncology drugs monitored for hallucination
KNOWN_DRUGS = [
    "osimertinib", "erlotinib", "gefitinib", "afatinib", "dacomitinib",
    "sotorasib", "adagrasib",
    "alectinib", "crizotinib", "ceritinib", "brigatinib", "lorlatinib",
    "dabrafenib", "trametinib", "vemurafenib",
    "cisplatin", "carboplatin", "pemetrexed", "paclitaxel", "docetaxel", "gemcitabine",
    "pembrolizumab", "nivolumab", "atezolizumab", "durvalumab", "ipilimumab",
    "trastuzumab", "pertuzumab", "bevacizumab", "cetuximab", "panitumumab"
]

# Genomic mutations monitored
KNOWN_MUTATIONS = [
    "egfr l858r", "egfr exon 19 del", "egfr exon 19 deletion", "egfr t790m", "egfr exon 20 ins",
    "kras g12c", "kras g12d", "kras g12v",
    "alk fusion", "alk rearrangement",
    "ros1 fusion", "ros1 rearrangement",
    "braf v600e", "braf mutation",
    "met amplification", "met exon 14 skipping",
    "ret fusion", "her2 mutation", "her2 amplification",
    "stk11 mutation", "stk11", "tp53 mutation", "tp53", "keap1 mutation"
]

# Adverse events and toxicities
KNOWN_ADVERSE_EVENTS = [
    "hepatotoxicity", "mucositis", "thrombocytopenia", "neutropenia",
    "peripheral neuropathy", "pneumonitis", "severe diarrhea", "diarrhea",
    "colitis", "nephrotoxicity", "rash", "fatigue", "fever", "dyspnea",
    "nausea", "vomiting", "anemia", "chills"
]

# Common symptoms
KNOWN_SYMPTOMS = [
    "shortness of breath", "chest discomfort", "persistent cough",
    "loss of appetite", "mild fatigue", "skin rash", "rash worsening",
    "nausea after treatment", "fever and chills"
]

# Prescriptive and treatment recommendation trigger phrases (unauthorized for an SLM summarizer)
UNAUTHORIZED_RECOMMENDATIONS = [
    "recommend starting", "should start", "recommend stopping", "should discontinue",
    "switch to", "increase dose", "decrease dose", "titrate to",
    "prescribe", "initiate therapy", "administer immediately", "advised to take",
    "patient should be treated with", "treatment recommendation", "plan of care requires",
    "indicated treatment is", "urgent prescription", "start patient on"
]

# Autonomous diagnosis trigger phrases
UNAUTHORIZED_DIAGNOSIS = [
    "confirms definitive diagnosis", "diagnosed as terminal", "autonomous diagnosis",
    "confirmed stage iv progression", "clinical verdict confirms", "pathologist concludes definitively"
]

RESEARCH_DISCLAIMER = (
    "RESEARCH PROTOTYPE NOTICE: This summary is generated by a clinical Small Language Model "
    "(SLM) for assistive summarization only. It does not provide autonomous clinical diagnosis, "
    "treatment prescription, or dosage modification. All statements must be verified by a licensed oncologist."
)


class ClinicalSummarySafetyGuardrail:
    """Post-generation clinical verification and safety guardrail engine."""

    def __init__(self, strict_mode: bool = True):
        self.strict_mode = strict_mode

    @staticmethod
    def _normalize(text: str) -> str:
        """Normalizes text for substring matching."""
        if not text:
            return ""
        # Lowercase, convert common punctuation and spaces
        cleaned = text.lower()
        cleaned = re.sub(r"[^\w\s\./-]", " ", cleaned)
        cleaned = re.sub(r"\s+", " ", cleaned).strip()
        return cleaned

    @staticmethod
    def extract_dosages(text: str) -> List[str]:
        """Extracts dosage expressions (e.g. '300mg', '200 mg/day', '5 mg BID')."""
        matches = re.findall(r"\b\d+(?:\.\d+)?\s*(?:mg|mg\/day|bid|mcg|g|units|iu)\b", text, flags=re.IGNORECASE)
        return [m.strip().lower() for m in matches]

    def validate(self, clinical_report: str, generated_summary: str) -> Dict[str, Any]:
        """
        Validates the generated summary against the source clinical report.

        Returns:
            Dict containing validation status, flagged violations, severity counts, and safety notices.
        """
        report_norm = self._normalize(clinical_report)
        summary_norm = self._normalize(generated_summary)

        flags: List[Dict[str, Any]] = []

        # -------------------------------------------------------------
        # 1. Drug Hallucination Check
        # -------------------------------------------------------------
        for drug in KNOWN_DRUGS:
            # Check if drug is mentioned in the summary
            pattern = rf"\b{re.escape(drug)}\b"
            if re.search(pattern, summary_norm):
                if not re.search(pattern, report_norm):
                    flags.append({
                        "category": "DRUG_HALLUCINATION",
                        "severity": "CRITICAL",
                        "entity": drug,
                        "message": f"Summary mentions drug '{drug}' which is absent from the source clinical report."
                    })

        # -------------------------------------------------------------
        # 2. Dosage Mismatch Check
        # -------------------------------------------------------------
        summary_dosages = self.extract_dosages(generated_summary)
        for dose in summary_dosages:
            # Check if numbers from the dose appear in the report
            numeric_parts = re.findall(r"\d+", dose)
            found_in_report = all(num in report_norm for num in numeric_parts)
            if not found_in_report:
                flags.append({
                    "category": "DOSAGE_MISMATCH",
                    "severity": "HIGH",
                    "entity": dose,
                    "message": f"Dosage specification '{dose}' in summary does not match any numerical values in source report."
                })

        # -------------------------------------------------------------
        # 3. Genomic Mutation Grounding Check
        # -------------------------------------------------------------
        for mut in KNOWN_MUTATIONS:
            if mut in summary_norm and mut not in report_norm:
                # Dissect key tokens (e.g. 'l858r', 'v600e', 'g12c')
                tokens = [t for t in mut.split() if len(t) >= 4 and not t.isdigit()]
                if not any(t in report_norm for t in tokens):
                    flags.append({
                        "category": "MUTATION_HALLUCINATION",
                        "severity": "HIGH",
                        "entity": mut,
                        "message": f"Genomic mutation '{mut}' appears in summary but is not documented in source report."
                    })

        # -------------------------------------------------------------
        # 4. Adverse Event & Symptom Grounding Check
        # -------------------------------------------------------------
        for ae in KNOWN_ADVERSE_EVENTS:
            # Only match distinct terms of length > 3
            if len(ae) > 3 and re.search(rf"\b{re.escape(ae)}\b", summary_norm):
                if not re.search(rf"\b{re.escape(ae)}\b", report_norm):
                    flags.append({
                        "category": "UNSUPPORTED_ADVERSE_EVENT",
                        "severity": "MEDIUM",
                        "entity": ae,
                        "message": f"Adverse event/toxicity '{ae}' mentioned in summary was not recorded in source report."
                    })

        # -------------------------------------------------------------
        # 5. Unauthorized Treatment Recommendations & Prescriptions
        # -------------------------------------------------------------
        for phrase in UNAUTHORIZED_RECOMMENDATIONS:
            pattern = rf"\b{re.escape(phrase)}\b"
            if re.search(pattern, summary_norm):
                flags.append({
                    "category": "UNAUTHORIZED_TREATMENT_RECOMMENDATION",
                    "severity": "CRITICAL",
                    "entity": phrase,
                    "message": f"Generated summary contains prescriptive directive ('{phrase}'). SLM is restricted to factual summarization."
                })

        # -------------------------------------------------------------
        # 6. Autonomous Diagnosis Detection
        # -------------------------------------------------------------
        for phrase in UNAUTHORIZED_DIAGNOSIS:
            if phrase in summary_norm:
                flags.append({
                    "category": "AUTONOMOUS_DIAGNOSIS_CLAIM",
                    "severity": "CRITICAL",
                    "entity": phrase,
                    "message": f"Generated summary contains autonomous diagnosis claim ('{phrase}')."
                })

        # Aggregate metrics
        critical_count = sum(1 for f in flags if f["severity"] == "CRITICAL")
        high_count = sum(1 for f in flags if f["severity"] == "HIGH")
        medium_count = sum(1 for f in flags if f["severity"] == "MEDIUM")
        passed = (critical_count == 0 and high_count == 0)

        # Build safe returned summary if critical hallucination occurred
        if not passed:
            safety_status = "flagged"
            flag_notes = "; ".join(f"{f['category']}: {f['entity']}" for f in flags if f['severity'] in ['CRITICAL', 'HIGH'])
            sanitized = f"{generated_summary}\n\n[GUARDRAIL WARNING: Potential unsupported content detected ({flag_notes}). Verify directly against source note.]"
        else:
            safety_status = "passed"
            sanitized = generated_summary

        return {
            "passed": passed,
            "safety_status": safety_status,
            "flags": flags,
            "metrics": {
                "total_flags": len(flags),
                "critical_flags": critical_count,
                "high_flags": high_count,
                "medium_flags": medium_count
            },
            "sanitized_summary": sanitized,
            "disclaimer": RESEARCH_DISCLAIMER
        }
